# Generated by Django 4.2 on 2023-04-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_category_servicetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='minimal_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_image1',
            field=models.ImageField(blank=True, null=True, upload_to='users/service_images', verbose_name='service_image1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_image2',
            field=models.ImageField(blank=True, null=True, upload_to='users/service_images', verbose_name='service_image1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_image3',
            field=models.ImageField(blank=True, null=True, upload_to='users/service_images', verbose_name='service_image1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_image4',
            field=models.ImageField(blank=True, null=True, upload_to='users/service_images', verbose_name='service_image1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_image5',
            field=models.ImageField(blank=True, null=True, upload_to='users/service_images', verbose_name='service_image1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(default='', max_length=100, verbose_name='specialization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='minimal_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
