# Generated by Django 4.2 on 2023-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_customuser_minimal_price_customuser_service_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='specialization'),
        ),
    ]
