# Generated by Django 4.2 on 2023-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_customuser_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='service_info',
            field=models.TextField(blank=True, null=True, verbose_name='service_info'),
        ),
    ]
