# Generated by Django 4.2 on 2023-04-12 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_chat_rename_updated_at_message_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='send_to',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
