# Generated by Django 4.2 on 2023-04-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_chat_send_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('R', 'Read'), ('D', 'Deleted')], default='S', max_length=1),
        ),
    ]
