# Generated by Django 4.2 on 2023-04-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_client_chat_send_to_remove_chat_freelancer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание исполнения'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='pending', max_length=255),
        ),
    ]
