# Generated by Django 4.2 on 2023-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_rename_user_orderfeedback_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeedback',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
