# Generated by Django 4.2 on 2023-04-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_order_city_order_country_order_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='order',
            name='required_skills',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.skills', verbose_name='skills'),
        ),
    ]
