# Generated by Django 4.2 on 2023-04-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_remove_order_required_skills_order_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='budget_currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('rub', 'RUB'), ('uzs', 'UZS')], default='1', max_length=3, verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='budget_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('hourly', 'Почасовая')], default='1', max_length=10, verbose_name='budget_type'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('payment_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('hourly', 'Почасовая')], max_length=10)),
                ('status', models.CharField(choices=[('fixed', 'Фиксированная'), ('hourly', 'Почасовая')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
            ],
        ),
    ]
