# Generated by Django 4.2 on 2023-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_order_budget_currency_order_budget_type_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='order',
            name='required_skills',
            field=models.TextField(default='1', verbose_name='required skills'),
            preserve_default=False,
        ),
    ]
