# Generated by Django 4.2 on 2023-04-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_order_required_skills_order_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='required_skills',
            field=models.CharField(max_length=255, verbose_name='required skills'),
        ),
    ]
