# Generated by Django 4.2 on 2023-04-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_order_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(default='', max_length=50, verbose_name='subtitle'),
            preserve_default=False,
        ),
    ]
