# Generated by Django 4.2 on 2023-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_category_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(null=True, upload_to='users/service_images', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='subtitle'),
        ),
    ]
