# Generated by Django 4.2 on 2023-04-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_category_options_alter_skills_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('last_transaction', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.wallet'),
        ),
    ]
