# Generated by Django 4.2 on 2023-04-14 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_wallet_customuser_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
