# Generated by Django 4.2 on 2023-04-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_remove_payment_payment_type_payment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('canceled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=10),
        ),
    ]
