# Generated by Django 4.2 on 2023-04-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='awards',
            field=models.TextField(blank=True, null=True, verbose_name='awards'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('canceled', 'Отменено'), ('completed', 'Успешно'), ('pending', 'Ожидание')], default='pending', max_length=10),
        ),
    ]
