# Generated by Django 4.2 on 2023-04-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_language_customuser_awards_customuser_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('canceled', 'Отменено'), ('pending', 'Ожидание'), ('completed', 'Успешно')], default='pending', max_length=10),
        ),
    ]
