# Generated by Django 4.2 on 2023-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_customuser_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('canceled', 'Отменено'), ('completed', 'Успешно'), ('pending', 'Ожидание')], default='pending', max_length=10),
        ),
    ]
